# -*- coding: utf-8 -*-
"""martha_model_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-BH0PI6IgXmy88WDAqY8KD_XBFB1Q5O
"""

from sklearn.svm import SVC
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"
column_names = ['ID', 'Diagnosis'] + [f'Feature_{i}' for i in range(1, 31)]
df = pd.read_csv(url, header=None, names=column_names)

# Drop ID column (not useful for training)
df.drop(columns=['ID'], inplace=True)

# Convert Diagnosis column to numerical (M = 1, B = 0)
df['Diagnosis'] = df['Diagnosis'].map({'M': 1, 'B': 0})

# Display basic stats
print(df.head())
print(df.info())
print(df.describe())

X = df.drop(columns=['Diagnosis'])
y = df['Diagnosis']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train a Support Vector Machine Model
svm_model = SVC(kernel="linear", random_state=42)
svm_model.fit(X_train, y_train)

# Predictions and Evaluation
y_pred_svm = svm_model.predict(X_test)

# Performance Metrics
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"SVM Accuracy: {accuracy_svm:.2f}")
print(classification_report(y_test, y_pred_svm))